parameters:
#    godana_tuto.example.class: Godana\TutoBundle\Example

services:
#    godana_tuto.example:
#        class: %godana_tuto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
